#!/bin/bash
# Bash completion support for Rake, Ruby Make.

export COMP_WORDBREAKS=${COMP_WORDBREAKS/\:/}

_rakecomplete() {
    if [ -f Rakefile ]; then
    	raketabs="$HOME/.raketabs"
    	if [ ! -d $raketabs ]; then
    		mkdir $raketabs
    	fi
    	raketasks=raketasks-$(pwd | sed -e "s|/|-|g")~
    	file="$raketabs/$raketasks"
        recent=`ls -t $file Rakefile **/*.rake 2> /dev/null | head -n 1`
        if [[ $recent != "${raketasks}" ]]; then
            rake --silent --tasks | cut -d " " -f 2 > "${file}"
        fi
        COMPREPLY=($(compgen -W "`cat \"${file}\"`" -- ${COMP_WORDS[COMP_CWORD]}))
        return 0
    fi
}

complete -o default -o nospace -F _rakecomplete rake

# vim:syntax=sh
