# vim:syntax=sh

SHELL_DIR=$(readlink $HOME/.bashrc | xargs dirname)/../shell
source $SHELL_DIR/bash/config
source $SHELL_DIR/aliases
source $SHELL_DIR/env
source $SHELL_DIR/functions

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
