set guioptions=egmt
set guioptions-=r
set fuopt=maxvert,maxhorz

if has("gui_macvim")

    let macvim_skip_cmd_opt_movement=1

    if has("autocmd")
        autocmd GUIEnter * set guifont=Bitstream\ Vera\ Sans\ Mono:h12
    endif

endif

colorscheme slate



