set guioptions=egmt
set guioptions-=r
set fuopt=maxvert,maxhorz

if has("gui_macvim")
    if has("autocmd")
        "autocmd GUIEnter * set guifont=Bitstream\ Vera\ Sans\ Mono:h12
        autocmd GUIEnter * set guifont=Monaco:h12
    endif

endif

"colorscheme molokai

